version: '3.7'
services:
  web:
    build:
      context: .
      args:
        BUILD_ENV: dev
    init: true
    environment:
      ALLOWED_HOSTS: 127.0.0.1,0.0.0.0,localhost
      DATABASE_URL: postgres://wagtail:wagtail@db:5432/wagtail # pragma: allowlist secret
      DJANGO_SETTINGS_MODULE: website.settings.dev
      MEDIA_DIR: /app/media/
      RECAPTCHA_PRIVATE_KEY: UPDATE_THIS # pragma: allowlist secret
      RECAPTCHA_PUBLIC_KEY: UPDATE_THIS
      REDIS_URL: redis://redis
      SECRET_KEY: local_dev_secret_key
      SECURE_SSL_REDIRECT: 'false'
      STATIC_DIR: /app/static/
      STATIC_URL: /static/
    command: tail -f /dev/null # do nothing forever - exec commands elsewhere
    ports:
      - 8000:8000 # runserver
    volumes:
      - ./README.md:/app/README.md:delegated,ro
      - ./docs:/app/docs:delegated,ro
      - ./manage.py:/app/manage.py:delegated,ro
      - ./website:/app/website:delegated,rw
      - ./media:/app/media:delegated,rw
      - ./poetry.lock:/app/poetry.lock:rw
      - ./pyproject.toml:/app/pyproject.toml:rw
      - ./website/static_compiled:/app/website/static_compiled:rw
      - ./public:/app/public:delegated,ro
    depends_on:
      - db
      - redis

  utils:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.utils
    tty: true
    volumes:
      - ./media:/app/media:delegated,rw
      - ./database_dumps:/app/database_dumps:delegated,rw
    command: tail -f /dev/null

  db:
    image: postgres:12.3
    expose:
      - 5432
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: wagtail # pragma: allowlist secret
      PGDATABASE: wagtail
      PGUSER: wagtail
      PGPASSWORD: wagtail # pragma: allowlist secret
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none
    volumes:
      - ./database_dumps:/app/database_dumps:delegated,rw

  redis:
    image: redis:3.0
    expose:
      - 6379
    logging:
      driver: none
