name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Black
      run: 
        pip install black
        && black . --diff --check
    - name: Flake8
      run:
        pip install flake8 
        && flake8 . --ignore=F401,F403
    - name: Isort
      run: 
        pip install isort==5.0.8
        && isort . --check --dif
  deploy-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a ${{ secrets.HEROKU_APP_STAGING }} web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_STAGING }} web 
    - name: Migrate
      run: heroku run python3 ./manage.py migrate -a ${{ secrets.HEROKU_APP_STAGING }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a ${{ secrets.HEROKU_APP_PRODUCTION }} web 
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_PRODUCTION }} web 
    - name: Migrate
      run: heroku run python3 ./manage.py migrate -a ${{ secrets.HEROKU_APP_PRODUCTION }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}